name: 'Nextcloud Upload File'
description: 'A GitHub Action to upload a file to Nextcloud.'
inputs:
  file_path:  
    description: 'Path of the file to be uploaded'
    required: true
  nextcloud_url:  
    description: 'URL of the Nextcloud server'
    required: true
  username:
    description: 'Username for Nextcloud'
    required: true
  password:
    description: 'Password for Nextcloud'
    required: true
  override:
    description: 'Set to true to overwrite the file if it exists (true/false)'
    required: false
    default: 'false'
  rename:
    description: 'Optional: New name for the file before upload'
    required: false
    default: '' # Empty string means no renaming
  zip:
    description: 'Set to true if the file should be zipped before upload (true/false)'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'blue'
