name: 'Upload File to Nextcloud'

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path of the file to upload'
        required: true
      nextcloud_url:
        description: 'Nextcloud WebDAV URL'
        required: true
      username:
        description: 'Nextcloud Username'
        required: true
      password:
        description: 'Nextcloud Password'
        required: true
      override:
        description: 'Overwrite the file if it exists (true/false)'
        required: false
        default: 'false'
      rename:
        description: 'Optional: New name for the file before upload'
        required: false
        default: ''
      zip:
        description: 'Set to true if the file should be zipped before upload (true/false)'
        required: false
        default: 'false'
      date:
        description: 'Set to true if the current date should be appended to the file name (true/false)'
        required: false
        default: 'false'
      time:
        description: 'Set to true if the current time should be appended after the date (if set) (true/false)'
        required: false
        default: 'false'

